/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FlipWords: typeof import('./components/FlipWords.vue')['default']
    HeadTitle: typeof import('./components/HeadTitle.vue')['default']
    MarqueeWords: typeof import('./components/MarqueeWords.vue')['default']
    VirtualList: typeof import('./components/VirtualList.vue')['default']
  }
}
